const app=document.getElementById('app');const KEY='pjokArenaUser';let user=JSON.parse(localStorage.getItem(KEY)||'null');let state={qs:[],i:0,score:0,xp:0,correct:0,answered:false,time:15,timer:null,mode:20};
function shell(content){app.innerHTML=`<div class="grid"></div><main class="wrap">${content}</main>`}
function register(){shell(`<section class="hero"><div class="logo">⚡ PJOK ARENA ⚡</div><h1>CLASS VII</h1><p>Cerdas Cermat PJOK — Arena Belajar Bergaya Gaming</p><div class="card" style="max-width:520px;margin:auto;text-align:left"><h2>🎮 Buat Profil Pemain</h2><label>Username</label><input id="u" placeholder="contoh: denny07"><label>Nama Lengkap</label><input id="n" placeholder="Nama lengkap"><label>Kelas</label><select id="k"><option>VII A</option><option>VII B</option><option>VII C</option><option>VII D</option><option>VII E</option><option>VII F</option><option>VII G</option></select><br><br><button class="btn" onclick="saveUser()">MULAI ARENA 🚀</button></div></section>`)}
function saveUser(){const u=document.getElementById('u').value.trim(),n=document.getElementById('n').value.trim(),k=document.getElementById('k').value;if(!u||!n)return alert('Username dan nama lengkap wajib diisi.');user={username:u,name:n,class:k,totalXP:0,totalScore:0,played:0,correct:0};localStorage.setItem(KEY,JSON.stringify(user));dashboard()}
function dashboard(){shell(`<div class="topbar"><div><div class="logo">PJOK ARENA</div><span class="small">Halo, ${esc(user.name)} • ${user.class}</span></div><button class="btn alt" style="width:auto" onclick="logout()">Keluar</button></div><div class="card"><h2>🔥 Selamat datang di Arena!</h2><div class="stats"><div class="stat">⭐ XP<br><b>${user.totalXP}</b></div><div class="stat">🏆 Skor<br><b>${user.totalScore}</b></div><div class="stat">🎯 Akurasi<br><b>${user.played?Math.round(user.correct/user.played*100):0}%</b></div></div><div class="menu"><div class="tile" onclick="startQuiz(10)">⚡ <b>Quick Match</b><br><span class="small">10 soal • cepat</span></div><div class="tile" onclick="startQuiz(20)">🔥 <b>Standard Match</b><br><span class="small">20 soal • rekomendasi</span></div><div class="tile" onclick="startQuiz(30)">💀 <b>Challenge</b><br><span class="small">30 soal • hardcore</span></div><div class="tile" onclick="leaderboard()">🏆 <b>Leaderboard</b><br><span class="small">Lihat peringkat lokal</span></div></div><p class="small" style="margin-top:20px">📚 Bank soal saat ini berisi ${QUESTIONS.length} soal yang bersumber dari contoh tes pada perangkat ajar.</p></div>`)}
function startQuiz(mode){state.mode=mode;state.qs=[...QUESTIONS].sort(()=>Math.random()-.5).slice(0,Math.min(mode,QUESTIONS.length));state.i=0;state.score=0;state.xp=0;state.correct=0;showQ()}
function showQ(){clearInterval(state.timer);state.answered=false;state.time=15;const q=state.qs[state.i];shell(`<div class="topbar"><button class="btn alt" style="width:auto" onclick="dashboard()">← Menu</button><div class="timer" id="timer">00:15</div></div><div class="card"><div class="quizHead"><b>SOAL ${state.i+1}/${state.qs.length}</b><span class="badge">${q.c}</span></div><div class="progress"><i style="width:${state.i/state.qs.length*100}%"></i></div><div class="qtext">${esc(q.q)}</div><div class="opts">${q.o.map((x,j)=>`<button class="opt" id="o${j}" onclick="answer(${j})">${String.fromCharCode(65+j)}. ${esc(x)}</button>`).join('')}</div><div id="feedback"></div></div>`);state.timer=setInterval(()=>{state.time--;document.getElementById('timer').textContent='00:'+String(state.time).padStart(2,'0');if(state.time<=0){clearInterval(state.timer);answer(-1)}},1000)}
function answer(j){if(state.answered)return;state.answered=true;clearInterval(state.timer);const q=state.qs[state.i],ok=j===q.a;if(j>=0)document.getElementById('o'+j).classList.add(ok?'correct':'wrong');document.getElementById('o'+q.a).classList.add('correct');let pts=ok?(q.d===2?30:20):0;state.score+=pts;state.xp+=pts;state.correct+=ok?1:0;document.getElementById('feedback').innerHTML=`<div class="feedback">${ok?'✅ BENAR! +'+pts+' poin':'❌ BELUM TEPAT'}<br>${esc(q.e)}<br><span class="small">Sumber: ${q.sourceRef}</span><br><br><button class="btn" onclick="nextQ()">${state.i+1===state.qs.length?'LIHAT HASIL':'SOAL BERIKUTNYA →'}</button></div>`}
function nextQ(){if(state.i+1<state.qs.length){state.i++;showQ()}else finish()}
function finish(){clearInterval(state.timer);user.totalXP+=state.xp;user.totalScore+=state.score;user.played+=state.qs.length;user.correct+=state.correct;localStorage.setItem(KEY,JSON.stringify(user));shell(`<div class="hero"><div class="card"><div class="logo">RESULT COMPLETE</div><h1>🎉 ${state.score}</h1><p>${state.correct} / ${state.qs.length} jawaban benar</p><div class="stats"><div class="stat">⭐ XP<br><b>+${state.xp}</b></div><div class="stat">🎯 Akurasi<br><b>${Math.round(state.correct/state.qs.length*100)}%</b></div><div class="stat">📚 Soal<br><b>${state.qs.length}</b></div></div><button class="btn" onclick="startQuiz(${state.mode})">MAIN LAGI 🔥</button><br><br><button class="btn alt" onclick="dashboard()">KEMBALI KE MENU</button></div></div>`)}
function leaderboard(){const fake=[['PERINGKAT SEPUH','Denny Agustiana S.Pd',999999999],['#1','Belum ada data',0],['#2','Belum ada data',0],['#3','Belum ada data',0]];shell(`<div class="topbar"><button class="btn alt" style="width:auto" onclick="dashboard()">← Menu</button><div class="logo">LEADERBOARD</div></div><div class="card"><h2>🏆 Peringkat Arena</h2>${fake.map((x,i)=>`<div class="rank"><span>${x[0]}<br><b>${x[1]}</b></span><b>${x[2]}</b></div>`).join('')}<p class="small">Versi GitHub Pages menyimpan skor pada perangkat masing-masing. Leaderboard online lintas HP membutuhkan database pada fase berikutnya.</p></div>`)}
function logout(){localStorage.removeItem(KEY);user=null;register()}function esc(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}if(user)dashboard();else register();
